name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          cd build
          git remote add origin https://github.com/brisa-pedronetto/ghp.git
          git pull
          git add .
          git commit -m 'New version'
          git branch --set-upstream master origin/master
          git push
        env:
          CI: true
